apiVersion: v1
kind: Service
metadata:
  name: hello-icp-load-test-service
spec:
  selector:
    app: hello-icp-load-test
  type: NodePort
  ports:
   - port: 9080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-icp-load-test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /request-task/*
        backend:
          serviceName: hello-icp-load-test-service
          servicePort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-icp-load-test-deployment
  labels:
    app: hello-icp-load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-icp-load-test
  template:
    metadata:
      labels:
        app: hello-icp-load-test
    spec:
      containers:
      - name: hello-icp-load-test
        image: dmoutinho/hello-icp-load-test:latest
        ports:
        - containerPort: 9080